# Dimensions and Shapes

In [1]:
# Arrays can be single dimension or multi dimensions
# Scalars are zero dimesnion
# Single dimension arrays can be refer as a Vector
# 2-D Arrays can be refer as Matrix (Since Matrix is little different from 2-D arrays in Numpy)
# 3-D Arrays can be refer as Tensor

In [3]:
import numpy as np


In [14]:
arr_0D = np.array(23)
arr_1D = np.arange(4)
arr_2D = np.array([[1,2,3],]*3)
arr_3D = np.array([[[1,2,3]],]*3)

print("0D: ",arr_0D,"\n1D: ", arr_1D,"\n2D:\n", arr_2D,"\n3D:\n", arr_3D)

"dimensions of arrays: ", arr_0D.ndim, arr_1D.ndim, arr_2D.ndim, arr_3D.ndim

0D:  23 
1D:  [0 1 2 3] 
2D:
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 
3D:
 [[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


('dimensions of arrays: ', 0, 1, 2, 3)

In [15]:
# for dimension ndim method is used numpy.ndarray.nidm or numpy.ndim(arr)

np.ndim(arr_1D)

1

In [17]:
# Shape
# shape is no of element per axis tuple

"shape of an 2D array: ", arr_2D.shape

('shape of an 2D array: ', (3, 3))

In [18]:
# (3,3) seen as in each axis there are 3 elements
# first axis = 0 refer as row, axis = 1 refer as column
print(arr_2D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
# shape of Scalar is empty tuple
# Shape of 1D arrays is (n, ) where n is no of elements
# shape of nD array is no of elements in each axis
np.shape(arr_0D), np.shape(arr_1D), np.shape(arr_3D)

((), (4,), (3, 1, 3))

In [23]:
# with use of ndarry.shape, we can change the shape of an array i.e.
arr_2D.shape = (1,3,1,3)

# one should be carefull that total number of element has to be same i.e.
# if array 'a' with shape (p, q) converted to array 'a_' with shape(m, n, a, b) then
# p * q = m * n* a * b

In [22]:
arr_2D

array([[[[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]]]])

In [24]:
# reshape method
# to change the shape of an array convinent method is reshape
arr_2D.reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
# original array not change 
# it just create view, same for np.reshape
# for some array if we don't know the any shape then can use -1 but not for all shapes i.e.

arr_2D.reshape(1, -1)
# -1 fullfill required elements in axis=2 

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [28]:
# reshape(1, -1) convert any array to row vector and reshape(-1, 1) convert any array to column vector
arr_2D.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [30]:
# original arrays will remain same 
np.reshape(arr_3D,(-1,1))
arr_3D

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [31]:
# Transpose of an array
# for vector it change row vector to column vector and vice versa
# for 2-D arrays shapes are swaps i.e. (a, b) change to (b, a)
# for n-dimension arrays , n>2 9 arrays with shape(n1,n2,....,ni-1,ni) changes to (ni, ni-1,.....,n1)
# original array remian same

arr_2D.T

array([[[[1],
         [1],
         [1]]],


       [[[2],
         [2],
         [2]]],


       [[[3],
         [3],
         [3]]]])

In [34]:
arr_2D.shape, arr_2D.T.shape

((1, 3, 1, 3), (3, 1, 3, 1))

In [38]:
# tranpose make array non contigous i.e.
a = np.arange(10).reshape(2,5)
b = a.T
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]))

In [42]:
b.shape = (10)


AttributeError: incompatible shape for a non-contiguous array

In [44]:
# for 1D array transpose remain same as original array
a = np.arange(10)
a, a.T


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [46]:
# for row or column vector
a = np.arange(10).reshape(-1,1)
a, a.T

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [53]:
# np.transpose is more generalized method then ndarry.T
# we can permute dimension of an array with use of np.tranpose

a = np.arange(12).reshape(2,3,2)
a.shape, np.transpose(a,(0,2,1)).shape
# (0,2,1) means 0 axis will be at 0th postion, at 1st position there will be 2nd axis and at 2nd postion 1st axis will be there
# permute shape (2,3,2) to (2,2,3) no element has to be same

((2, 3, 2), (2, 2, 3))